# Generated by Django 4.2.3 on 2024-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadeddocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextEntry',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_person',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='EDR',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
